# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
    - name: artifactory publish
      run: |
        npm install -g npm-force-resolutions
        jfrog rt bce adzerk-management-sdk-js ${GITHUB_REF##*/}
        jfrog rt npmci npm
        npm run build --if-present
        npm --no-git-tag-version version prerelease --preid=${GITHUB_REF##*/}
        jfrog rt npmp npm
      env:
        CI_USERNAME_PASSWORD: ${{secrets.ci_username_password}}
        CI: true
